name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # Chạy mỗi khi bạn push code lên branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        # Vì file pom.xml của bạn nằm trong thư mục con demo-app
        run: mvn clean package --file demo-app/pom.xml